name: OoD
channels:
  - gurobi
  - pytorch
  - anaconda
  - conda-forge
  - https://repo.anaconda.com/pkgs/main/
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2024.11.26=h06a4308_0
  - certifi=2024.8.30=py39h06a4308_0
  - cffi=1.15.1=py39h74dc2b5_0
  - comm=0.1.2=py39h06a4308_0
  - cryptography=39.0.1=py39h9ce1e76_0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - faiss=1.7.4=py39cuda112h460e57a_0_cuda
  - faiss-gpu=1.7.4=h788eb59_0
  - ffmpeg=4.3=hf484d3e_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gurobi=12.0.0=py39_0
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.19.2=py39hb070fc8_0
  - ipython=8.11.0=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - jupyter_core=4.12.0=py39hf3d152e_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=12_linux64_mkl
  - libdeflate=1.17=h5eee18b_0
  - libfaiss=1.7.4=cuda112hb18a002_0_cuda
  - libfaiss-avx2=1.7.4=cuda112h1234567_0_cuda
  - libffi=3.3=he6710b0_2
  - libgcc-ng=13.2.0=h77fa898_7
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - liblapack=3.9.0=12_linux64_mkl
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.23.5=py39h14f4228_0
  - numpy-base=1.23.5=py39h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=22.0=py39h06a4308_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py39h06a4308_0
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.13.1=py3.9_cpu_0
  - pytorch-mutex=1.0=cpu
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.1=h5082296_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.13.1=py39_cpu
  - tqdm=4.64.1=py39h06a4308_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - tzdata=2022g=h04d1e81_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - widgetsnbextension=4.0.5=pyhd8ed1ab_0
  - xz=5.2.10=h5eee18b_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.3.0
    - accelerate==1.2.1
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - allennlp==2.10.1
    - antlr4-python3-runtime==4.9.3
    - anyio==4.7.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - astunparse==1.6.3
    - async-lru==2.0.4
    - async-timeout==4.0.2
    - autoattack==0.1
    - babel==2.16.0
    - base58==2.1.1
    - beautifulsoup4==4.12.3
    - bleach==6.0.0
    - blis==0.7.11
    - bokeh==2.4.3
    - boto3==1.38.3
    - botocore==1.38.3
    - cached-path==1.1.6
    - cachetools==5.2.0
    - catalogue==2.0.10
    - chardet==5.1.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cloudpickle==2.2.1
    - colorama==0.4.6
    - colorcet==3.0.1
    - colored==1.4.4
    - commonmark==0.9.1
    - contourpy==1.0.6
    - cycler==0.11.0
    - cymem==2.0.11
    - dask==2023.3.1
    - datasets==2.8.0
    - datashader==0.14.4
    - datashape==0.5.2
    - defusedxml==0.7.1
    - dill==0.3.6
    - docker-pycreds==0.4.0
    - einops==0.8.1
    - et-xmlfile==1.1.0
    - evaluate==0.4.0
    - exceptiongroup==1.2.2
    - fairscale==0.4.6
    - filelock==3.7.1
    - flatbuffers==23.3.3
    - fonttools==4.38.0
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - fsspec==2024.10.0
    - gast==0.4.0
    - gdown==5.1.0
    - geotorch==0.3.0
    - gitdb==4.0.12
    - gitpython==3.1.44
    - google-api-core==2.24.2
    - google-auth==2.39.0
    - google-auth-oauthlib==0.4.6
    - google-cloud-core==2.4.3
    - google-cloud-storage==2.19.0
    - google-crc32c==1.7.1
    - google-pasta==0.2.0
    - google-resumable-media==2.7.2
    - googleapis-common-protos==1.70.0
    - grpcio==1.51.1
    - h11==0.14.0
    - h5py==3.8.0
    - higher==0.2.1
    - holoviews==1.15.4
    - httpcore==1.0.7
    - httpx==0.28.1
    - huggingface-hub==0.30.2
    - hydra-core==1.3.2
    - icecream==2.1.3
    - imageio==2.26.1
    - iniconfig==2.1.0
    - isoduration==20.11.0
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.2.0
    - json5==0.10.0
    - jsonnet==0.20.0
    - jsonpickle==3.0.1
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter-client==8.6.3
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.2
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.3.3
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - keras==2.11.0
    - kiwisolver==1.4.4
    - langcodes==3.5.0
    - language-data==1.3.0
    - lazy-loader==0.2
    - libclang==15.0.6.1
    - llvmlite==0.39.1
    - lmdb==1.4.1
    - locket==1.0.0
    - loguru==0.7.2
    - marisa-trie==1.2.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matlab==0.1
    - matplotlib==3.6.2
    - mistune==3.0.2
    - more-itertools==9.0.0
    - mpmath==1.3.0
    - multidict==6.0.3
    - multipledispatch==0.6.0
    - multiprocess==0.70.14
    - murmurhash==1.0.12
    - music21==8.1.0
    - nbclient==0.10.1
    - nbconvert==7.16.4
    - networkx==3.0
    - nltk==3.9.1
    - notebook-shim==0.2.4
    - numba==0.56.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - openai==0.27.6
    - opencv-python==4.9.0.80
    - openpyxl==3.0.10
    - opt-einsum==3.3.0
    - overrides==7.7.0
    - pandas==1.5.2
    - pandocfilters==1.5.1
    - panel==0.14.4
    - param==1.13.0
    - partd==1.3.0
    - pathlib-abc==0.1.1
    - pathtools==0.1.2
    - pathy==0.11.0
    - pillow==9.3.0
    - pip==24.0
    - pluggy==1.5.0
    - preshed==3.0.9
    - prometheus-client==0.21.1
    - promise==2.3
    - proto-plus==1.26.1
    - protobuf==3.20.3
    - pyarrow==10.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyautoattack==0.2.0
    - pyct==0.5.0
    - pydantic==1.8.2
    - pydot==3.0.4
    - pygments==2.13.0
    - pynndescent==0.5.8
    - pyparsing==3.0.9
    - pytest==8.3.5
    - python-graphviz==0.20.3
    - python-json-logger==3.2.0
    - pytz==2022.7
    - pyviz-comms==2.2.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==26.2.0
    - referencing==0.35.1
    - regex==2022.10.31
    - requests==2.32.3
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==12.6.0
    - robustbench==1.1.1
    - rpds-py==0.22.3
    - rsa==4.9
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.7
    - s3transfer==0.12.0
    - sacremoses==0.1.1
    - safetensors==0.4.5
    - scikit-image==0.20.0
    - scikit-learn==1.6.1
    - scipy==1.9.1
    - seaborn==0.12.1
    - send2trash==1.8.3
    - sentencepiece==0.2.0
    - sentry-sdk==2.27.0
    - setproctitle==1.3.5
    - setuptools==65.5.0
    - shortuuid==1.0.13
    - sklearn==0.0.post1
    - smart-open==6.4.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - soupsieve==2.6
    - spacy==3.3.3
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.5.1
    - stefutils==0.20.4
    - sty==1.0.4
    - sympy==1.12
    - tabulate==0.9.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.6.2.2
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==1.1.0
    - terminado==0.18.1
    - thinc==8.0.17
    - threadpoolctl==3.1.0
    - tifffile==2023.3.21
    - timm==1.0.9
    - tinycss2==1.4.0
    - tokenizers==0.11.1
    - tomli==2.2.1
    - toolz==0.12.0
    - torch==1.13.1
    - torchdiffeq==0.2.5
    - torchvision==0.13.1
    - tornado==6.4.2
    - transformers==4.20.1
    - typer==0.4.2
    - types-python-dateutil==2.9.0.20241206
    - typing-extensions==4.13.2
    - uri-template==1.3.0
    - urllib3==1.26.13
    - wandb==0.12.21
    - wasabi==0.10.1
    - webcolors==24.11.1
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - werkzeug==2.2.2
    - wheel==0.37.1
    - wrapt==1.15.0
    - xarray==2023.2.0
    - xxhash==3.1.0
    - yamlpath==3.8.0
    - yarl==1.8.2
prefix: /home/xysong/.conda/envs/OoD
